//
//  EspressokarteTests.swift
//  EspressokarteTests
//
//  Created by Timo Kuehne on 07.01.26.
//

import CoreLocation
import Testing

@testable import Espressokarte

// MARK: - Cafe Model Tests

struct CafeModelTests {

    @Test func cafeInitialization() {
        let cafe = Cafe(
            id: "test-cafe-1",
            name: "Test Cafe",
            address: "Test Street 1, Munich",
            latitude: 48.1351,
            longitude: 11.5820,
            currentPrice: 2.80
        )

        #expect(cafe.id == "test-cafe-1")
        #expect(cafe.name == "Test Cafe")
        #expect(cafe.address == "Test Street 1, Munich")
        #expect(cafe.latitude == 48.1351)
        #expect(cafe.longitude == 11.5820)
        #expect(cafe.currentPrice == 2.80)
        #expect(cafe.priceHistory.isEmpty)
    }

    @Test func cafeCoordinate() {
        let cafe = Cafe(
            id: "test",
            name: "Test",
            address: "Address",
            latitude: 48.1351,
            longitude: 11.5820
        )

        #expect(cafe.coordinate.latitude == 48.1351)
        #expect(cafe.coordinate.longitude == 11.5820)
    }

    @Test func cafeFormattedPriceWithValue() {
        let cafe = Cafe(
            id: "test",
            name: "Test",
            address: "Address",
            latitude: 48.0,
            longitude: 11.0,
            currentPrice: 2.80
        )

        #expect(cafe.formattedPrice == "€2.80")
    }

    @Test func cafeFormattedPriceNil() {
        let cafe = Cafe(
            id: "test",
            name: "Test",
            address: "Address",
            latitude: 48.0,
            longitude: 11.0,
            currentPrice: nil
        )

        #expect(cafe.formattedPrice == nil)
    }

    @Test func cafeLatestPriceRecord() {
        let oldRecord = PriceRecord(
            id: "old",
            price: 2.50,
            date: Date().addingTimeInterval(-86400),
            addedBy: "user1",
            addedByName: "User 1"
        )

        let newRecord = PriceRecord(
            id: "new",
            price: 2.80,
            date: Date(),
            addedBy: "user2",
            addedByName: "User 2"
        )

        let cafe = Cafe(
            id: "test",
            name: "Test",
            address: "Address",
            latitude: 48.0,
            longitude: 11.0,
            currentPrice: 2.80,
            priceHistory: [oldRecord, newRecord]
        )

        #expect(cafe.latestPriceRecord?.id == "new")
        #expect(cafe.latestPriceRecord?.price == 2.80)
    }

    @Test func cafeFromMapItemData() {
        let mapItem = MapItemData(
            id: "map-item-1",
            name: "Map Cafe",
            address: "Map Street 1",
            latitude: 48.1371,
            longitude: 11.5754
        )

        let cafe = Cafe.from(mapItem: mapItem)

        #expect(cafe.id == "map-item-1")
        #expect(cafe.name == "Map Cafe")
        #expect(cafe.address == "Map Street 1")
        #expect(cafe.latitude == 48.1371)
        #expect(cafe.longitude == 11.5754)
        #expect(cafe.currentPrice == nil)
        #expect(cafe.priceHistory.isEmpty)
    }

    @Test func cafeEquality() {
        let cafe1 = Cafe(
            id: "same-id",
            name: "Cafe 1",
            address: "Address 1",
            latitude: 48.0,
            longitude: 11.0
        )

        let cafe2 = Cafe(
            id: "same-id",
            name: "Cafe 1",
            address: "Address 1",
            latitude: 48.0,
            longitude: 11.0
        )

        #expect(cafe1 == cafe2)
    }
}

// MARK: - PriceRecord Model Tests

struct PriceRecordModelTests {

    @Test func priceRecordInitialization() {
        let record = PriceRecord(
            id: "record-1",
            price: 2.50,
            date: Date(),
            addedBy: "user-123",
            addedByName: "Test User",
            note: "Great coffee!"
        )

        #expect(record.id == "record-1")
        #expect(record.price == 2.50)
        #expect(record.addedBy == "user-123")
        #expect(record.addedByName == "Test User")
        #expect(record.note == "Great coffee!")
    }

    @Test func priceRecordFormattedPrice() {
        let record = PriceRecord(
            price: 3.20,
            addedBy: "user",
            addedByName: "User"
        )

        #expect(record.formattedPrice == "€3.20")
    }

    @Test func priceRecordFormattedPriceWithDecimals() {
        let record = PriceRecord(
            price: 2.00,
            addedBy: "user",
            addedByName: "User"
        )

        #expect(record.formattedPrice == "€2.00")
    }

    @Test func priceRecordAutoGeneratedId() {
        let record1 = PriceRecord(
            price: 2.50,
            addedBy: "user",
            addedByName: "User"
        )

        let record2 = PriceRecord(
            price: 2.50,
            addedBy: "user",
            addedByName: "User"
        )

        #expect(record1.id != record2.id)
    }

    @Test func priceRecordNilNote() {
        let record = PriceRecord(
            price: 2.50,
            addedBy: "user",
            addedByName: "User",
            note: nil
        )

        #expect(record.note == nil)
    }

    @Test func priceRecordEquality() {
        let date = Date()
        let record1 = PriceRecord(
            id: "same-id",
            price: 2.50,
            date: date,
            addedBy: "user",
            addedByName: "User"
        )

        let record2 = PriceRecord(
            id: "same-id",
            price: 2.50,
            date: date,
            addedBy: "user",
            addedByName: "User"
        )

        #expect(record1 == record2)
    }
}

// MARK: - MapItemData Tests

struct MapItemDataTests {

    @Test func mapItemDataInitialization() {
        let item = MapItemData(
            id: "item-1",
            name: "Coffee Shop",
            address: "Main Street 5, Munich",
            latitude: 48.1351,
            longitude: 11.5820
        )

        #expect(item.id == "item-1")
        #expect(item.name == "Coffee Shop")
        #expect(item.address == "Main Street 5, Munich")
        #expect(item.latitude == 48.1351)
        #expect(item.longitude == 11.5820)
    }

    @Test func mapItemDataCoordinate() {
        let item = MapItemData(
            id: "item",
            name: "Shop",
            address: "Address",
            latitude: 48.1371,
            longitude: 11.5754
        )

        #expect(item.coordinate.latitude == 48.1371)
        #expect(item.coordinate.longitude == 11.5754)
    }

    @Test func mapItemDataEquality() {
        let item1 = MapItemData(
            id: "same",
            name: "Shop",
            address: "Address",
            latitude: 48.0,
            longitude: 11.0
        )

        let item2 = MapItemData(
            id: "same",
            name: "Shop",
            address: "Address",
            latitude: 48.0,
            longitude: 11.0
        )

        #expect(item1 == item2)
    }
}

// MARK: - LocalCacheManager Tests

struct LocalCacheManagerTests {

    @Test func cacheAndLoadCafes() {
        let cacheManager = LocalCacheManager.shared

        // Clear any existing cache
        cacheManager.clearCache()

        // Create test cafes
        let cafes = [
            Cafe(
                id: "cafe-1",
                name: "Cafe One",
                address: "Address 1",
                latitude: 48.1351,
                longitude: 11.5820,
                currentPrice: 2.50
            ),
            Cafe(
                id: "cafe-2",
                name: "Cafe Two",
                address: "Address 2",
                latitude: 48.1371,
                longitude: 11.5754,
                currentPrice: 3.00
            ),
        ]

        // Cache cafes
        cacheManager.cacheCafes(cafes)

        // Load cached cafes
        let loadedCafes = cacheManager.loadCachedCafes()

        #expect(loadedCafes.count == 2)
        #expect(loadedCafes[0].id == "cafe-1")
        #expect(loadedCafes[0].name == "Cafe One")
        #expect(loadedCafes[0].currentPrice == 2.50)
        #expect(loadedCafes[1].id == "cafe-2")
        #expect(loadedCafes[1].name == "Cafe Two")

        // Clean up
        cacheManager.clearCache()
    }

    @Test func clearCache() {
        let cacheManager = LocalCacheManager.shared

        // Cache a cafe
        let cafe = Cafe(
            id: "test",
            name: "Test",
            address: "Address",
            latitude: 48.0,
            longitude: 11.0
        )
        cacheManager.cacheCafes([cafe])

        // Clear cache
        cacheManager.clearCache()

        // Verify empty
        let loadedCafes = cacheManager.loadCachedCafes()
        #expect(loadedCafes.isEmpty)
    }

    @Test func lastSyncDateUpdates() {
        let cacheManager = LocalCacheManager.shared

        // Clear cache
        cacheManager.clearCache()
        #expect(cacheManager.lastSyncDate == nil)

        // Cache something
        cacheManager.cacheCafes([])

        // Should have a sync date now
        #expect(cacheManager.lastSyncDate != nil)

        // Clean up
        cacheManager.clearCache()
    }

    @Test func loadEmptyCache() {
        let cacheManager = LocalCacheManager.shared
        cacheManager.clearCache()

        let cafes = cacheManager.loadCachedCafes()
        #expect(cafes.isEmpty)
    }
}

// MARK: - Cafe Annotation Tests

struct CafeAnnotationTests {

    @Test func annotationFromCafe() {
        let cafe = Cafe(
            id: "cafe-1",
            name: "Test Cafe",
            address: "Test Address",
            latitude: 48.1351,
            longitude: 11.5820,
            currentPrice: 2.80
        )

        let annotation = CafeAnnotation(cafe: cafe)

        #expect(annotation.id == cafe.id)
        #expect(annotation.title == "€2.80")
        #expect(annotation.subtitle == "Test Cafe")
        #expect(annotation.coordinate.latitude == 48.1351)
        #expect(annotation.coordinate.longitude == 11.5820)
    }

    @Test func annotationWithoutPrice() {
        let cafe = Cafe(
            id: "cafe-1",
            name: "Test Cafe",
            address: "Test Address",
            latitude: 48.1351,
            longitude: 11.5820,
            currentPrice: nil
        )

        let annotation = CafeAnnotation(cafe: cafe)

        #expect(annotation.title == "No price")
    }
}

// MARK: - Encoding/Decoding Tests

struct CodingTests {

    @Test func cafeEncodingDecoding() throws {
        let originalCafe = Cafe(
            id: "cafe-1",
            name: "Test Cafe",
            address: "Test Address",
            latitude: 48.1351,
            longitude: 11.5820,
            currentPrice: 2.80,
            priceHistory: [
                PriceRecord(
                    id: "record-1",
                    price: 2.80,
                    date: Date(),
                    addedBy: "user-1",
                    addedByName: "User 1",
                    note: "Test note"
                )
            ]
        )

        let encoder = JSONEncoder()
        let data = try encoder.encode(originalCafe)

        let decoder = JSONDecoder()
        let decodedCafe = try decoder.decode(Cafe.self, from: data)

        #expect(decodedCafe.id == originalCafe.id)
        #expect(decodedCafe.name == originalCafe.name)
        #expect(decodedCafe.address == originalCafe.address)
        #expect(decodedCafe.latitude == originalCafe.latitude)
        #expect(decodedCafe.longitude == originalCafe.longitude)
        #expect(decodedCafe.currentPrice == originalCafe.currentPrice)
        #expect(decodedCafe.priceHistory.count == 1)
        #expect(decodedCafe.priceHistory[0].price == 2.80)
    }

    @Test func priceRecordEncodingDecoding() throws {
        let originalRecord = PriceRecord(
            id: "record-1",
            price: 2.50,
            date: Date(),
            addedBy: "user-123",
            addedByName: "Test User",
            note: "Great espresso"
        )

        let encoder = JSONEncoder()
        let data = try encoder.encode(originalRecord)

        let decoder = JSONDecoder()
        let decodedRecord = try decoder.decode(PriceRecord.self, from: data)

        #expect(decodedRecord.id == originalRecord.id)
        #expect(decodedRecord.price == originalRecord.price)
        #expect(decodedRecord.addedBy == originalRecord.addedBy)
        #expect(decodedRecord.addedByName == originalRecord.addedByName)
        #expect(decodedRecord.note == originalRecord.note)
    }
}

// MARK: - Price Validation Tests

struct PriceValidationTests {

    @Test func validPriceRange() {
        // Test various price points
        let validPrices: [Double] = [0.50, 1.00, 1.50, 2.00, 2.50, 3.00, 4.00, 5.00]

        for price in validPrices {
            let isValid = price > 0 && price < 20
            #expect(isValid == true, "Price \(price) should be valid")
        }
    }

    @Test func invalidPriceZero() {
        let price = 0.0
        let isValid = price > 0 && price < 20
        #expect(isValid == false)
    }

    @Test func invalidPriceNegative() {
        let price = -1.0
        let isValid = price > 0 && price < 20
        #expect(isValid == false)
    }

    @Test func invalidPriceTooHigh() {
        let price = 25.0
        let isValid = price > 0 && price < 20
        #expect(isValid == false)
    }
}
